- name: using variable
  hosts: localhost
  
  tasks:
  - name: checking variables
    vars:
      Course: AWS from task
      Trainee: Raghava from task
    ansible.builtin.debug:
      msg: "Hi, My course is {{Course}}, Trainee is {{Trainee}}"