- name: using variable
  hosts: localhost
  vars:
    Course: AWS from vars
    Trainee: Raghava from vars
  tasks:
   - name: checking variable
     vars:
        Course: AWS from task
        Trainee: Raghava from task
     ansible.builtin.debug:
        msg: "Hi, My course is {{Course}}, Trainee is {{Trainee}}"