- name: using variable
  hosts: localhost
  tasks:
    vars_prompt:
     - name: Enter username
       msg: Enter username
       private: false
     - name: Enter password
       msg: Enter password
       private: True
  
    ansible.builtin.debug:
      msg: "Hi, Your username is {{Course}}, password is {{Trainee}}"