- name: using variable
  hosts: localhost
  vars_prompt:
    - name: Username
      prompt: Enter username
      private: false
    - name: Password
      prompt: Enter password
      private: True
  tasks:
      ansible.builtin.debug:
        msg: "Hi, Your username is {{Username}}, password is {{Password}}"