- name: using variable
  hosts: localhost
  vars_prompt:
  - name: babu
    prompt: Enter babu
    private: false
  - name: papa
    prompt: Enter papa
    private: true
  tasks:
    - name: Checking Details
      ansible.builtin.debug:
        msg: "Hi, Your username is {{babu}}, password is {{papa}}"