- name: using variable
  hosts: localhost
  tasks:
    vars_prompt:
     - name: Enter username
       Username: Enter username
       private: false
     - name: Enter password
       Password: Enter password
       private: True
  
    ansible.builtin.debug:
      msg: "Hi, Your username is {{Username}}, password is {{Password}}"