- name: using variable
  hosts: localhost
  vars:
    Name: Raghava
    Trainer: yes      
    skills:
      - devops
      - aws
      - MI
    Experience:
    DevOps: 6
    aws: 5
    MI: 3

  tasks:
  - name: Mentioning your skills
    ansible.builtin.debug:
        msg: "skills is {{skills}}"

  - name: Mentioning your Experience
    ansible.builtin.debug:
        msg: "Overall experience is {{Experience}}"

  - name: Giving trainer Name
    ansible.builtin.debug:
        msg: "Trainer name is {{Name}}"

  - name: Giving Boolean value
    ansible.builtin.debug:
        msg: "Is he trainer: {{Trainer}}"





