- name: using variable
  hosts: localhost
  become: yes
  tasks:
  - name: installing package
    ansible.builtin.package:
      name: {{item}}
      state: present

    loop:
     - nginx
     - mysql
     - python