- name: using variable
  hosts: localhost
  become: yes
  tasks:
  - name: installing package
    ansible.builtin.yum:
      name: "{{item}}"
      state: present

    loop:
     - nginx
     - mysql
     - python